// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXOuqvmUKqMANOF2isVpLo3iaZJ2Uh7E',
    appId: '1:747651759824:web:fa8bc220e88cfe849668d5',
    messagingSenderId: '747651759824',
    projectId: 'smartfarm-app-fe0a9',
    authDomain: 'smartfarm-app-fe0a9.firebaseapp.com',
    storageBucket: 'smartfarm-app-fe0a9.appspot.com',
    measurementId: 'G-3TCKQ3CXV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCluC2ZuRPF3wpmBcF3bUePqaOWm2HFcak',
    appId: '1:747651759824:android:895cca63d7db91ab9668d5',
    messagingSenderId: '747651759824',
    projectId: 'smartfarm-app-fe0a9',
    storageBucket: 'smartfarm-app-fe0a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVrQj9SRh4FJlnPCbJJ1FucrBPdDZ81TE',
    appId: '1:747651759824:ios:1f22eef012cbc6eb9668d5',
    messagingSenderId: '747651759824',
    projectId: 'smartfarm-app-fe0a9',
    storageBucket: 'smartfarm-app-fe0a9.appspot.com',
    iosClientId: '747651759824-8a17sn6bppsnm4lh8cls5e99qefhsoe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVrQj9SRh4FJlnPCbJJ1FucrBPdDZ81TE',
    appId: '1:747651759824:ios:1f22eef012cbc6eb9668d5',
    messagingSenderId: '747651759824',
    projectId: 'smartfarm-app-fe0a9',
    storageBucket: 'smartfarm-app-fe0a9.appspot.com',
    iosClientId: '747651759824-8a17sn6bppsnm4lh8cls5e99qefhsoe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalYearProject',
  );
}
